Education/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
     path('', include('student.urls')),
    path('teacher/', include('teacher.urls'))
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

student/urls.py
from django.urls import path
from . import views

app_name = "student"

urlpatterns = [
    path('home/', views.index, name = 'index'), # /
    path('', views.signin, name = 'signin'), # /signin
    path('login/', views.login, name = 'login'), # /login    
    path('logout/', views.logout_student, name = 'logout'), # /logout    
    path('profile/', views.student_profile, name = 'profile'), # /profile    
    path('verify-email/<slug:id>', views.verify_email, name = 'verify-email'), # /verify-email/:username
    path('resend-otp/', views.resend_otp, name = 'resend-otp'), # /resend-otp  
    path('matiere/', views.matieres, name = 'matieres'), # /matiere
    path('cours/', views.cours, name = 'cours'), # /cours
    path('cours/<int:cours_id>', views.show_cours, name = 'show-cours'), # /cours/id
    path('exercice/', views.exercices, name = 'exercices'), # /exercice
    path('exercice/<int:exercice_id>', views.show_exercice, name = 'show-exercice'), # /exercice/id
    path('matiere/<int:matiere_id>', views.show_matiere, name = 'show-matiere'), # /matiere/id
    path('score/<int:exercice_id>', views.score, name = 'score'), # /score/id
    path('payement/', views.payement, name = 'payement'), # /payement
    path('payement/info', views.info_payement, name = 'info'), # /payement/info
    path('success/', views.success, name = 'success'), # /success
    path('cancel/', views.cancel, name = 'cancel'), # /cancel   
]

teacher/urls.py
from django.urls import path
from . import views

app_name = 'teacher'

urlpatterns = [
    path('', views.signin, name = 'signin'), # /
    path('login', views.login, name = 'login'), # /teacher/login
    path('logout', views.teacher_logout, name = 'logout'), # /teacher/logout
    path('topic', views.topic, name = 'topic'), # /teacher/topic
    path('lesson', views.lesson, name = 'lesson'), # /teacher/lesson
    path('exercice', views.exam, name = 'exercice'), # /teacher/exercice
    path('student', views.student, name = 'student'), # /teacher/student
    path('transaction', views.transaction, name = 'transaction'), # /teacher/transaction
    path('create-topic', views.create_topic, name = 'create-topic'), # /teacher/create-topic
    path('create-exercice/qcm/', views.create_qcm, name = 'create-qcm'), # /teacher/create-exercice/qcm
    path('create-exercice/question-reponse/', views.create_qr, name = 'create-qr'), # /teacher/create-exercice/question-reponse
    path('exercice/delete/<int:exercice_id>', views.delete_exercice, name = 'delete_exercice'), # /teacher/exercice/delete/id
    path('create-lesson', views.create_lesson, name = 'create-lesson'), # /teacher/create-lesson
    path('topic/delete/<int:topic_id>', views.delete_topic, name = 'delete_topic'), # /teacher/topic/delete/id
    path('topic/edit/<int:topic_id>', views.edit_topic, name = 'edit_topic'), # /teacher/topic/edit/id
    path('lesson/delete/<int:lesson_id>', views.delete_lesson, name = 'delete_lesson'), # /teacher/lesson/delete/id
    path('lesson/edit/<int:lesson_id>', views.edit_lesson, name = 'edit_lesson'), # /teacher/lesson/edit/id
]

student/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.conf import settings
from teacher.models import Exercice
import secrets

class Student(AbstractUser):
    email = models.EmailField(unique=True)
    phonenumber = models.CharField(max_length=15, unique=True)
    image = models.ImageField(upload_to='profile/', default='profile/default-profile.jpg')
    role = models.CharField(max_length=25, default='student')
    point = models.IntegerField(default=0)
    niveau = models.CharField(max_length=25, default='Débutant')

    LEVEL_CHOICES = [
        ('6e', '6e'),
        ('5e', '5e'),
        ('4e', '4e'),
        ('3e', '3e'),
        ('2nde', '2nde'),
        ('1ere', '1ere'),
        ('Tle', 'Tle'),
    ]

    level = models.CharField(max_length=4, choices=LEVEL_CHOICES, null=True)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['first_name', 'last_name', 'username']

    def __str__(self) -> str:
        return self.email
    
Student._meta.get_field('groups').related_name = 'student_groups'
Student._meta.get_field('user_permissions').related_name = 'student_user_permissions'

class Otp(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    code = models.CharField(max_length=6, default=secrets.token_hex(3))
    created_at = models.DateTimeField(auto_now=True)
    expire_at = models.DateTimeField(blank=True, null=True)

class Score(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    exercice = models.ForeignKey(Exercice, on_delete=models.CASCADE)
    score = models.CharField(max_length=7)

class Transaction(models.Model):
    user = models.ForeignKey(Student, on_delete=models.CASCADE)
    transID = models.CharField(max_length=50, null=False)
    montant = models.IntegerField(default=100)
    status = models.CharField(max_length=20, default="pending")
    token = models.CharField(max_length=255)

teacher/models.py
from django.db import models

class Matiere(models.Model):
    nom_matiere = models.CharField(max_length=20, null=False)
    img_matiere = models.ImageField(upload_to='Matiere/', default='Matiere/default-matiere.jpg')
    nombre_cours = models.IntegerField(default=0, null=True)

    LEVEL_CHOICES = [
        ('6e', '6e'),
        ('5e', '5e'),
        ('4e', '4e'),
        ('3e', '3e'),
        ('2nde', '2nde'),
        ('1ere', '1ere'),
        ('Tle', 'Tle'),
    ]
    level = models.CharField(max_length=4, choices=LEVEL_CHOICES)

class Cours(models.Model):
    de_matiere = models.ForeignKey(Matiere, on_delete = models.CASCADE)
    nom_cours = models.CharField(max_length=30, null=False)
    img_cours = models.ImageField(upload_to='Cours_img/', default='Cours_img/default-cours.jpg')
    file_cours = models.FileField(upload_to='Cours_file/')

class Exercice(models.Model):
    cours = models.ForeignKey(Cours, on_delete = models.CASCADE)
    img_exercice = models.ImageField(upload_to='exercice/', default='exercice/default-exerice.jpg')
    titre = models.CharField(max_length=50)
    type_question = models.CharField(max_length=25)
    questions = models.JSONField(default=None)

student/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login as student_login, authenticate, get_user_model, logout, update_session_auth_hash
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.core.mail import send_mail
from student.models import Student, Otp, Score, Transaction
from teacher.models import Matiere, Cours, Exercice
from django.utils import timezone
from django.shortcuts import get_object_or_404
import random
import json
import requests
from datetime import datetime

@login_required
def index(request):
    try:
        transaction = Transaction.objects.get(user=request.user.id)
    except Transaction.DoesNotExist:
            transaction = None
    if transaction is None or transaction.status != "completed":
        return redirect('student:info')

    matieres = Matiere.objects.filter(level=request.user.level)

    if matieres.exists():
        cours_all = Cours.objects.filter(de_matiere__in=matieres)
    else:
        cours_all = None

    if cours_all.exists():
        exercices = Exercice.objects.filter(cours__in=cours_all)
    else:
        exercices = None

    context = {
        "matieres": matieres,
        "lessons": cours_all,
        "data": exercices,
        "student": request.user
    }
    return render(request, "index.html", context)

def signin(request):
    if request.method == 'POST':
        lastname = request.POST.get('lastname', '')
        firstname = request.POST.get('firstname', '')
        email = request.POST.get('email', '')
        password1 = request.POST.get('password1', '')
        password2 = request.POST.get('password2', '')
        phonenumber = request.POST.get('phonenumber', '')
        level = request.POST.get('level')
        print(level)
        if password1 != password2 :
            messages.error(request, 'Les deux mots de passe ne sont pas les mêmes.')
            return render(request, 'signin.html')

        if Student.objects.filter(email=email).exists():
            messages.error(request, 'Email déjà existants')
            return render(request, 'signin.html')
        
        if Student.objects.filter(phonenumber=phonenumber).exists():
            messages.error(request, 'Ce numéro est déjà utiliseé.')
            return render(request, 'signin.html')

        user = Student.objects.create_user(username=email, first_name=firstname, last_name=lastname, email=email, password=password1, phonenumber=phonenumber, level=level)
        user.save()
        return redirect('student:verify-email', id=user.id) 
    
    return render(request, "signin.html")

def login(request):
    if request.method == 'POST':
        username = request.POST.get('username', '')
        password = request.POST.get('password', '')

        try:
            student = Student.objects.get(email=username)
        except Student.DoesNotExist:
            try:
                student = Student.objects.get(phonenumber=username)
            except Student.DoesNotExist:
                return redirect('student:login')
        
        try:
            transaction = Transaction.objects.get(user=student.id)
        except Transaction.DoesNotExist:
            transaction = None

        if student is not None:        
            user = authenticate(request, username=student.username, password=password)
            if user is not None:
                student_login(request, user)
                if transaction is None or transaction.status != "completed":
                    return redirect('student:info')
                
                return redirect('student:index')
        else:
            messages.warning(request, "Email, numero de telephone ou mot de passe non valide.")
            return render(request, 'login.html')
    return render(request, 'login.html')

@login_required
def logout_student(request):
    logout(request)
    return redirect('student:login')

def verify_email(request, id):
    if request.method == 'POST':
        user = get_user_model().objects.get(id=id)
        otp = Otp.objects.all().last()
        
        code_1 = request.POST.get('code-1', '')
        code_2 = request.POST.get('code-2', '')
        code_3 = request.POST.get('code-3', '')
        code_4 = request.POST.get('code-4', '')
        code_5 = request.POST.get('code-5', '')
        code_6 = request.POST.get('code-6', '')
        code = str(code_1) + str(code_2) + str(code_3) + str(code_4) + str(code_5) + str(code_6)

        if otp.code == code:
            if otp.expire_at > timezone.now():
                user.is_active = True
                user.save()

                return redirect('student:login')

            else:
                messages.warning(request, 'L\'OTP a expiré, recuperez un nouveau OTP !')
                return redirect('student:verify-email', id=user.id)
    
        else:
            messages.warning(request, 'OTP saisit invalide, entrez un OTP valide !')
            return redirect('student:verify-email', id=user.id)

    return render(request, 'verify_email.html')

def resend_otp(request):
    if request.method == 'POST':
        email = request.POST.get('email', '')
        try:
            user = get_user_model().objects.get(email=email)
            # user = get_object_or_404(Student, email = email)
            if user is not None:
                otp = Otp.objects.create(user=user, expire_at=timezone.now() + timezone.timedelta(minutes=5))
                subject = 'Email verification'
                message = f"""
                            Hi {user.username}, here is your OTP {otp.code}
                            It expires in 5 minutes, use the url below to redirect back to the website
                            Http://127.0.0.1:8000/verify-email/{user.id}
                        """
                sender = 'bitibalyclementalex@gmail.com'
                receiver = [user.email,]

                send_mail(subject, message, sender, receiver, fail_silently=False)

                messages.success(request, '')
                return redirect('student:verify-email', id=user.id)
        except Student.DoesNotExist:
            messages.warning(request, 'The email does not exist in the database')
            return redirect('student:resend-otp')
    
    return render(request, 'resend.html')

@login_required
def matieres(request):
    try:
        transaction = Transaction.objects.get(user=request.user.id)
    except Transaction.DoesNotExist:
            transaction = None
    
    if transaction is None or transaction.status != "completed":
        return redirect('student:info')
     
    context = {
        "data": Matiere.objects.filter(level=request.user.level),
        "student": request.user
    }
    return render(request, 'matieres.html', context)

@login_required
def cours(request):
    try:
        transaction = Transaction.objects.get(user=request.user.id)
    except Transaction.DoesNotExist:
            transaction = None
    
    if transaction is None or transaction.status != "completed":
        return redirect('student:info')

    matieres = Matiere.objects.filter(level=request.user.level)

    if matieres.exists():
        cours = Cours.objects.filter(de_matiere__in=matieres)
    else:
        cours = None
    context = {
        "data": cours,
        "student": request.user
    }
    return render(request, 'cours.html', context)

@login_required
def exercices(request):
    try:
        transaction = Transaction.objects.get(user=request.user.id)
    except Transaction.DoesNotExist:
            transaction = None
    
    if transaction is None or transaction.status != "completed":
        return redirect('student:info')

    matieres = Matiere.objects.filter(level=request.user.level)
    # matiere = matieres[0].id if matieres else None
    if matieres.exists():
        cours_all = Cours.objects.filter(de_matiere__in=matieres)
    else:
        cours_all = None

    if cours_all.exists():
        exercices = Exercice.objects.filter(cours__in=cours_all)
    else:
        exercices = None

    context = {
        "data": exercices,
        "student": request.user
    }
    return render(request, 'exercice.html', context)

@login_required
def show_matiere(request, matiere_id):
    try:
        transaction = Transaction.objects.get(user=request.user.id)
    except Transaction.DoesNotExist:
            transaction = None
    
    if transaction is None or transaction.status != "completed":
        return redirect('student:info')

    context = {
        "data": Cours.objects.filter(de_matiere = matiere_id),
        "matiere": Matiere.objects.get(id=matiere_id),
        "student": request.user
    }
    return render(request, 'show_matiere.html', context)

@login_required
def show_cours(request, cours_id):
    try:
        transaction = Transaction.objects.get(user=request.user.id)
    except Transaction.DoesNotExist:
            transaction = None
    
    if transaction is None or transaction.status != "completed":
        return redirect('student:info')

    cours = Cours.objects.get(id=cours_id)
    cours_all = Cours.objects.filter(id=cours_id)
    exercices = Exercice.objects.filter(cours__in=cours_all)
    context = {
        "cours": cours,
        "data": exercices,
        "student": request.user
    }

    if cours.file_cours.name.endswith(".pdf"):
        return render(request, "cours_pdf.html", context)
    elif cours.file_cours.name.endswith(".mp4"):
        return render(request, "cours_video.html", context)

    return redirect('student:cours')

@login_required
def show_exercice(request, exercice_id):
    try:
        transaction = Transaction.objects.get(user=request.user.id)
    except Transaction.DoesNotExist:
            transaction = None
    
    if transaction is None or transaction.status != "completed":
        return redirect('student:info')

    exercice = Exercice.objects.get(id=exercice_id)

    context = {
        "data": exercice,

teacher/templates/exams.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Teacher</title>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Assistant:wght@200..800&family=Freeman&family=Montserrat:ital,wght@0,100..900;1,100..900&family=Open+Sans:ital,wght@0,300..800;1,300..800&display=swap" rel="stylesheet">
    <script src="https://cdn.tailwindcss.com"></script>
    <script src="{% static 'scripts/tailwind.js' %}"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.2/css/all.min.css" integrity="sha512-SnH5WK+bZxgPHs44uWIX+LLJAJ9/2PkPKZ5QiAj6Ta86w+fsb2TkcmfRyVX3pBnMFcV7oQPJkl9QevSCWr3W6A==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <script>
        tailwind.config = {
          theme: {
            extend: {
              colors: {
                clifford: '#da373d',
                primary: '#ff7e84',
                secondary: '#30bead',
                tertiary: '#ffbc1f',
                redShade: '#8861db',
                dark: '#0c1327',
                fourth: '#dcf2ef',
                fiveth: '#ffebec',
                sixth: '#ffffff',
                seventh: '#e8edf5'
              },
              flex: {
                '30': '1 1 30rem',

              },
              gridTemplateColumns: {
                'auto-fit': 'repeat(auto-fit, minmax(250px, 1fr))',
              },
              screens: {
                'max-950': {'max': '950px'},
                'max-700': {'max': '700px'},
                'max-585': {'max': '585px'},
                'max-495': {'max': '495px'},
                'max-395': {'max': '395px'},
              },
              spacing: {
                '10p': '10%',
                'low': '68px'
              },
              height: {
                '30': '30%',
                '40': '40%',
                '60': '60%',
                '70': '70%',
                '90': '90%',
                '110': '110vh'
              },
              width: {
                '30': '30%',
                '40': '40%',
                '60': '60%',
                '70': '70%',
                '90': '90%',
                '110': '110vh'
              },
            }
          }
        }
    </script>
</head>
<body>
    <header class="w-full p-2 bg-white fixed z-50 flex items-center justify-center">
        <nav class="w-full flex items-center justify-between">
            <a href="#" class="text-2xl font-bold text-primary transition duration-300 ease-out hover:text-xl">EduMin</a>           
            <div class="flex items-center gap-4">
                <img class="w-12 h-12 p-1 rounded-full ring-2 ring-gray-300 object-cover" src="{% static 'img/default-profile.jpg' %}" alt="profile">
                <div class="text-lg font-bold">
                    <div>{{teacher.last_name}} {{teacher.first_name}}</div>
                </div>
            </div>
        </nav>
    </header>
    <section class="w-full h-screen bg-seventh pt-low flex items-center justify-between gap-2">
        <div class="bg-white w-1/6 h-full p-4 flex items-center flex-col gap-8">          
            <div class="mt-4 w-full flex items-center gap-4">
                <img class="w-12 h-12 rounded-full object-cover" src="{% static 'img/default-profile.jpg' %}" alt="">
                <div class="font-bold">
                    <div>{{teacher.last_name}} {{teacher.first_name}}</div>
                    <div class="text-sm text-gray-500">Teacher</div>
                </div>
            </div>
            <div class="w-full flex items-center justify-center gap-2 flex-col">
              <a href="{% url 'teacher:topic' %}" class="rounded-lg w-full p-2 flex items-center gap-4 hover:bg-emerald-50 hover:text-green-800">
                <div class="fa-solid fa-book text-xl"></div>
                <span class="text-xl font-semibold">Matieres</span>
              </a>
              <a href="{% url 'teacher:lesson' %}" class="rounded-lg w-full p-2 flex items-center gap-4 hover:bg-emerald-50 hover:text-green-800">
                <div class="fa-solid fa-book-open text-xl"></div>
                <span class="text-xl font-semibold">Cours</span>
              </a>
              <a href="{% url 'teacher:exercice' %}" class="rounded-lg w-full p-2 flex items-center gap-4 bg-emerald-50 hover:bg-emerald-50 hover:text-green-800">
                <i class="fa-solid fa-book-open-reader text-xl text-green-800"></i>
                <span class="text-xl font-semibold text-green-800">Exercices</span>
              </a>
              <a href="{% url 'teacher:student' %}" class="rounded-lg w-full p-2 flex items-center gap-4 hover:bg-emerald-50 hover:text-green-800">
                <div class="fa-solid fa-users text-xl"></div>
                <span class="text-xl font-semibold">Élèves</span>
              </a>
              <a href="{% url 'teacher:transaction' %}" class="rounded-lg w-full p-2 flex items-center gap-4 hover:bg-emerald-50 hover:text-green-800">
                <div class="fa-solid fa-money-bill-transfer text-xl"></div>
                <span class="text-xl font-semibold">Transaction</span>
              </a>
            </div>
            <div class="border-solid border-t-2 w-full h-16 relative -bottom-60 flex items-center justify-center hover:text-red-400">
              <a href="{% url 'teacher:logout' %}" class="rounded-lg w-full p-2 flex items-center gap-4">
                <i class="fa-solid fa-right-from-bracket text-xl"></i>
                <span class="text-xl font-semibold">Déconnextion</span>
              </a>
            </div>
        </div>
        <div class="p-4 w-5/6 h-full flex items-center gap-4 flex-col">
          <h1 class="self-start mt-4 text-5xl text-dark font-bold">Exercice</h1>
          <div class="w-full h-14 p-4 bg-white rounded-lg flex items-center justify-end gap-4">
            <a href="{% url 'teacher:create-qcm' %}" class="p-2 w-36 rounded bg-green-700 text-white font-semibold">
              <div class="fa-solid fa-plus"></div>
              Exercice QCM
            </a>
            <a href="{% url 'teacher:create-qr' %}" class="p-2 w-42 rounded bg-green-700 text-white font-semibold">
              <div class="fa-solid fa-plus"></div>
              Exercice question réponse
            </a>
          </div>
          

          <div class="relative overflow-x-auto shadow-md w-full rounded-lg">
            {% if exercices %}
              <table class="w-full text-sm text-left rtl:text-right text-gray-500">
                  <thead class="text-xs text-gray-700 uppercase bg-gray-50">
                    <tr>
                        <th scope="col" class="px-6 py-3">
                            Numéro
                        </th>
                        <th scope="col" class="px-6 py-3">
                          image
                        </th>
                        <th scope="col" class="px-6 py-3">
                            nom Cours
                        </th>
                        <th scope="col" class="px-6 py-3">
                          Titre de l'exercice
                        </th>
                        <th scope="col" class="px-6 py-3">
                            Action
                        </th>
                    </tr>
                  </thead>
                  <tbody>
                    {% for exercice in exercices %}
                      <tr class="odd:bg-white even:bg-gray-50 border-b hover:bg-gray-100">
                          <th scope="row" class="px-6 py-4 font-medium text-gray-900 whitespace-nowrap">
                              {{ forloop.counter }}
                          </th>
                          <td class="px-6 py-4">
                            {% if exercice.img_exercice %}
                              <img class="w-10 h-10 rounded object-cover" src="{{ exercice.img_exercice.url }}" alt="Current avatar">
                            {% else %}
                              <img class="w-10 h-10 rounded object-cover" src="{% static 'img/default-exercice.jpg' %}" alt="Default avatar">
                            {% endif %}
                          </td>
                          <td class="px-6 py-4">
                              {{ exercice.cours.nom_cours }}
                          </td>
                          <td class="px-6 py-4">
                            {{exercice.titre}}
                          </td>
                          <td class="px-6 py-4">
                              <a href="{% url 'teacher:delete_exercice' exercice.id %}" class="font-medium text-lg mr-2">
                                <span class="bg-red-100 text-red-800 font-semibold me-2 px-5 py-0.5 rounded transition duration-300 ease-in-out hover:bg-red-200">Delete</span>
                              </a>
                          </td>
                      </tr>
                    {% endfor %}
                  </tbody>
              </table>
            {% else %}
              <p class="text-2xl font-bold text-center">Aucun Cours</p>
            {%endif%}
          </div>
        </div>
    </section>
</body>
</html>

teacher/templates/teacher_login.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Connexion</title>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Assistant:wght@200..800&family=Freeman&family=Montserrat:ital,wght@0,100..900;1,100..900&family=Open+Sans:ital,wght@0,300..800;1,300..800&display=swap" rel="stylesheet">
    <script src="https://cdn.tailwindcss.com"></script>
    <script src="{% static 'scripts/tailwind.js' %}"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.2/css/all.min.css" integrity="sha512-SnH5WK+bZxgPHs44uWIX+LLJAJ9/2PkPKZ5QiAj6Ta86w+fsb2TkcmfRyVX3pBnMFcV7oQPJkl9QevSCWr3W6A==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <script>
        tailwind.config = {
          theme: {
            extend: {
              colors: {
                clifford: '#da373d',
                primary: '#ff7e84',
                secondary: '#30bead',
                tertiary: '#ffbc1f',
                redShade: '#8861db',
                dark: '#0c1327',
                fourth: '#dcf2ef',
                fiveth: '#ffebec',
                sixth: '#ffffff'
              },
              flex: {
                '30': '1 1 30rem',

              },
              gridTemplateColumns: {
                'auto-fit': 'repeat(auto-fit, minmax(250px, 1fr))',
              },
              screens: {
                'max-950': {'max': '950px'},
                'max-700': {'max': '700px'},
                'max-585': {'max': '585px'},
                'max-495': {'max': '495px'},
                'max-395': {'max': '395px'},
              },
              spacing: {
                '10p': '10%',
              },
              height: {
                '30': '30%',
                '40': '40%',
                '60': '60%',
                '70': '70%',
                '90': '90%',
                '110': '110vh'
              },
              width: {
                '30': '30%',
                '40': '40%',
                '60': '60%',
                '70': '70%',
                '90': '90%',
                '110': '110vh'
              },
            }
          }
        }
    </script>
</head>
<body class="bg-primary w-full h-screen">
    <div class="w-full h-full rounded-lg flex items-center justify-center max-700:w-full">
        <div class="border border-solid boder-gray-800 w-40 h-full max-950:hidden">
            <img src="{% static 'img/connexion.jpg' %}" class="w-full h-full object-cover" alt="pink-yellow">
        </div>
        <div class="py-4 px-8 w-60 h-full bg-gradient-to-r from-fourth to-green-50 flex items-center justify-center flex-col gap-7 max-950:w-full">
            <span class="text-2xl font-bold">Connexion Enseignant</span>
            <form class="w-4/6 max-585:w-full" method="post">
              {% csrf_token %}
                <div class="relative z-0 w-full mb-5 group">
                    <input type="email" name="email" id="floating_email" class="block py-2.5 px-0 w-full text-sm text-black bg-transparent border-0 border-b-2 border-gray-300 appearance-none  focus:outline-none focus:ring-0 focus:border-primary peer" placeholder=" " required />
                    <label for="floating_email" class="peer-focus:font-medium absolute text-sm text-gray-500 dark:text-gray-400 duration-300 transform -translate-y-6 scale-75 top-3 -z-10 origin-[0] peer-focus:start-0 rtl:peer-focus:translate-x-1/4 rtl:peer-focus:left-auto peer-focus:text-primary peer-placeholder-shown:scale-100 peer-placeholder-shown:translate-y-0 peer-focus:scale-75 peer-focus:-translate-y-6">Email address</label>
                </div>
                <div class="relative z-0 w-full mb-5 group">
                    <input type="password" name="password" id="floating_password" class="block py-2.5 px-0 w-full text-sm text-dark bg-transparent border-0 border-b-2 border-gray-300 appearance-none  focus:outline-none focus:ring-0 focus:border-primary peer" placeholder=" " required />
                    <label for="floating_password" class="peer-focus:font-medium absolute text-sm text-gray-500 dark:text-gray-400 duration-300 transform -translate-y-6 scale-75 top-3 -z-10 origin-[0] peer-focus:start-0 rtl:peer-focus:translate-x-1/4 peer-focus:text-primary peer-placeholder-shown:scale-100 peer-placeholder-shown:translate-y-0 peer-focus:scale-75 peer-focus:-translate-y-6">Password</label>
                </div>                
                <div class="w-full flex items-center justify-center">
                  <button type="submit" class="text-white transition duration-300 ease bg-secondary hover:scale-95 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm w-full sm:w-40 px-5 py-2.5 text-center">Submit</button>
                </div>
            </form>
            <p class="text-lg text-gray-500">
              Vous n'avez pas de compte?
              <a href="{% url 'teacher:signin' %}" class="underline transition duration-300 ease-in-out hover:font-bold hover:text-dark">Sign in</a>
            </p>
        </div>
    </div>
</body>
</html>