Education/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
     path('', include('student.urls')),
    path('teacher/', include('teacher.urls'))
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

student/urls.py
from django.urls import path
from . import views

app_name = "student"

urlpatterns = [
    path('home/', views.index, name = 'index'), # /
    path('', views.signin, name = 'signin'), # /signin
    path('login/', views.login, name = 'login'), # /login    
    path('logout/', views.logout_student, name = 'logout'), # /logout    
    path('profile/', views.student_profile, name = 'profile'), # /profile    
    path('verify-email/<slug:id>', views.verify_email, name = 'verify-email'), # /verify-email/:username
    path('resend-otp/', views.resend_otp, name = 'resend-otp'), # /resend-otp  
    path('matiere/', views.matieres, name = 'matieres'), # /matiere
    path('cours/', views.cours, name = 'cours'), # /cours
    path('cours/<int:cours_id>', views.show_cours, name = 'show-cours'), # /cours/id
    path('exercice/', views.exercices, name = 'exercices'), # /exercice
    path('exercice/<int:exercice_id>', views.show_exercice, name = 'show-exercice'), # /exercice/id
    path('matiere/<int:matiere_id>', views.show_matiere, name = 'show-matiere'), # /matiere/id
    path('score/<int:exercice_id>', views.score, name = 'score'), # /score/id
    path('payement/', views.payement, name = 'payement'), # /payement
    path('payement/info', views.info_payement, name = 'info'), # /payement/info
    path('success/', views.success, name = 'success'), # /success
    path('cancel/', views.cancel, name = 'cancel'), # /cancel   
]

student/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.conf import settings
from teacher.models import Exercice
import secrets

class Student(AbstractUser):
    email = models.EmailField(unique=True)
    phonenumber = models.CharField(max_length=15, unique=True)
    image = models.ImageField(upload_to='profile/', default='profile/default-profile.jpg')
    role = models.CharField(max_length=25, default='student')
    point = models.IntegerField(default=0)
    niveau = models.CharField(max_length=25, default='Débutant')

    LEVEL_CHOICES = [
        ('6e', '6e'),
        ('5e', '5e'),
        ('4e', '4e'),
        ('3e', '3e'),
        ('2nde', '2nde'),
        ('1ere', '1ere'),
        ('Tle', 'Tle'),
    ]

    level = models.CharField(max_length=4, choices=LEVEL_CHOICES, null=True)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['first_name', 'last_name', 'username']

    def __str__(self) -> str:
        return self.email
    
Student._meta.get_field('groups').related_name = 'student_groups'
Student._meta.get_field('user_permissions').related_name = 'student_user_permissions'

class Otp(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    code = models.CharField(max_length=6, default=secrets.token_hex(3))
    created_at = models.DateTimeField(auto_now=True)
    expire_at = models.DateTimeField(blank=True, null=True)

class Score(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    exercice = models.ForeignKey(Exercice, on_delete=models.CASCADE)
    score = models.CharField(max_length=7)

class Transaction(models.Model):
    user = models.ForeignKey(Student, on_delete=models.CASCADE)
    transID = models.CharField(max_length=50, null=False)
    montant = models.IntegerField(default=100)
    status = models.CharField(max_length=20, default="pending")
    token = models.CharField(max_length=255)

student/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login as student_login, authenticate, get_user_model, logout, update_session_auth_hash
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.core.mail import send_mail
from student.models import Student, Otp, Score, Transaction
from teacher.models import Matiere, Cours, Exercice
from django.utils import timezone
from django.shortcuts import get_object_or_404
import random
import json
import requests
from datetime import datetime

@login_required
def index(request):
    try:
        transaction = Transaction.objects.get(user=request.user.id)
    except Transaction.DoesNotExist:
            transaction = None
    if transaction is None or transaction.status != "completed":
        return redirect('student:info')

    matieres = Matiere.objects.filter(level=request.user.level)

    if matieres.exists():
        cours_all = Cours.objects.filter(de_matiere__in=matieres)
    else:
        cours_all = None

    if cours_all.exists():
        exercices = Exercice.objects.filter(cours__in=cours_all)
    else:
        exercices = None

    context = {
        "matieres": matieres,
        "lessons": cours_all,
        "data": exercices,
        "student": request.user
    }
    return render(request, "index.html", context)

def signin(request):
    if request.method == 'POST':
        lastname = request.POST.get('lastname', '')
        firstname = request.POST.get('firstname', '')
        email = request.POST.get('email', '')
        password1 = request.POST.get('password1', '')
        password2 = request.POST.get('password2', '')
        phonenumber = request.POST.get('phonenumber', '')
        level = request.POST.get('level')
        print(level)
        if password1 != password2 :
            messages.error(request, 'Les deux mots de passe ne sont pas les mêmes.')
            return render(request, 'signin.html')

        if Student.objects.filter(email=email).exists():
            messages.error(request, 'Email déjà existants')
            return render(request, 'signin.html')
        
        if Student.objects.filter(phonenumber=phonenumber).exists():
            messages.error(request, 'Ce numéro est déjà utiliseé.')
            return render(request, 'signin.html')

        user = Student.objects.create_user(username=email, first_name=firstname, last_name=lastname, email=email, password=password1, phonenumber=phonenumber, level=level)
        user.save()
        return redirect('student:verify-email', id=user.id) 
    
    return render(request, "signin.html")

def login(request):
    if request.method == 'POST':
        username = request.POST.get('username', '')
        password = request.POST.get('password', '')

        try:
            student = Student.objects.get(email=username)
        except Student.DoesNotExist:
            try:
                student = Student.objects.get(phonenumber=username)
            except Student.DoesNotExist:
                return redirect('student:login')
        
        try:
            transaction = Transaction.objects.get(user=student.id)
        except Transaction.DoesNotExist:
            transaction = None

        if student is not None:        
            user = authenticate(request, username=student.username, password=password)
            if user is not None:
                student_login(request, user)
                if transaction is None or transaction.status != "completed":
                    return redirect('student:info')
                
                return redirect('student:index')
        else:
            messages.warning(request, "Email, numero de telephone ou mot de passe non valide.")
            return render(request, 'login.html')
    return render(request, 'login.html')

@login_required
def logout_student(request):
    logout(request)
    return redirect('student:login')

def verify_email(request, id):
    if request.method == 'POST':
        user = get_user_model().objects.get(id=id)
        otp = Otp.objects.all().last()
        
        code_1 = request.POST.get('code-1', '')
        code_2 = request.POST.get('code-2', '')
        code_3 = request.POST.get('code-3', '')
        code_4 = request.POST.get('code-4', '')
        code_5 = request.POST.get('code-5', '')
        code_6 = request.POST.get('code-6', '')
        code = str(code_1) + str(code_2) + str(code_3) + str(code_4) + str(code_5) + str(code_6)

        if otp.code == code:
            if otp.expire_at > timezone.now():
                user.is_active = True
                user.save()

                return redirect('student:login')

            else:
                messages.warning(request, 'L\'OTP a expiré, recuperez un nouveau OTP !')
                return redirect('student:verify-email', id=user.id)
    
        else:
            messages.warning(request, 'OTP saisit invalide, entrez un OTP valide !')
            return redirect('student:verify-email', id=user.id)

    return render(request, 'verify_email.html')

def resend_otp(request):
    if request.method == 'POST':
        email = request.POST.get('email', '')
        try:
            user = get_user_model().objects.get(email=email)
            # user = get_object_or_404(Student, email = email)
            if user is not None:
                otp = Otp.objects.create(user=user, expire_at=timezone.now() + timezone.timedelta(minutes=5))
                subject = 'Email verification'
                message = f"""
                            Hi {user.username}, here is your OTP {otp.code}
                            It expires in 5 minutes, use the url below to redirect back to the website
                            Http://127.0.0.1:8000/verify-email/{user.id}
                        """
                sender = 'bitibalyclementalex@gmail.com'
                receiver = [user.email,]

                send_mail(subject, message, sender, receiver, fail_silently=False)

                messages.success(request, '')
                return redirect('student:verify-email', id=user.id)
        except Student.DoesNotExist:
            messages.warning(request, 'The email does not exist in the database')
            return redirect('student:resend-otp')
    
    return render(request, 'resend.html')

@login_required
def matieres(request):
    try:
        transaction = Transaction.objects.get(user=request.user.id)
    except Transaction.DoesNotExist:
            transaction = None
    
    if transaction is None or transaction.status != "completed":
        return redirect('student:info')
     
    context = {
        "data": Matiere.objects.filter(level=request.user.level),
        "student": request.user
    }
    return render(request, 'matieres.html', context)

@login_required
def cours(request):
    try:
        transaction = Transaction.objects.get(user=request.user.id)
    except Transaction.DoesNotExist:
            transaction = None
    
    if transaction is None or transaction.status != "completed":
        return redirect('student:info')

    matieres = Matiere.objects.filter(level=request.user.level)

    if matieres.exists():
        cours = Cours.objects.filter(de_matiere__in=matieres)
    else:
        cours = None
    context = {
        "data": cours,
        "student": request.user
    }
    return render(request, 'cours.html', context)

@login_required
def exercices(request):
    try:
        transaction = Transaction.objects.get(user=request.user.id)
    except Transaction.DoesNotExist:
            transaction = None
    
    if transaction is None or transaction.status != "completed":
        return redirect('student:info')

    matieres = Matiere.objects.filter(level=request.user.level)
    # matiere = matieres[0].id if matieres else None
    if matieres.exists():
        cours_all = Cours.objects.filter(de_matiere__in=matieres)
    else:
        cours_all = None

    if cours_all.exists():
        exercices = Exercice.objects.filter(cours__in=cours_all)
    else:
        exercices = None

    context = {
        "data": exercices,
        "student": request.user
    }
    return render(request, 'exercice.html', context)

@login_required
def show_matiere(request, matiere_id):
    try:
        transaction = Transaction.objects.get(user=request.user.id)
    except Transaction.DoesNotExist:
            transaction = None
    
    if transaction is None or transaction.status != "completed":
        return redirect('student:info')

    context = {
        "data": Cours.objects.filter(de_matiere = matiere_id),
        "matiere": Matiere.objects.get(id=matiere_id),
        "student": request.user
    }
    return render(request, 'show_matiere.html', context)

@login_required
def show_cours(request, cours_id):
    try:
        transaction = Transaction.objects.get(user=request.user.id)
    except Transaction.DoesNotExist:
            transaction = None
    
    if transaction is None or transaction.status != "completed":
        return redirect('student:info')

    cours = Cours.objects.get(id=cours_id)
    cours_all = Cours.objects.filter(id=cours_id)
    exercices = Exercice.objects.filter(cours__in=cours_all)
    context = {
        "cours": cours,
        "data": exercices,
        "student": request.user
    }

    if cours.file_cours.name.endswith(".pdf"):
        return render(request, "cours_pdf.html", context)
    elif cours.file_cours.name.endswith(".mp4"):
        return render(request, "cours_video.html", context)

    return redirect('student:cours')

@login_required
def show_exercice(request, exercice_id):
    try:
        transaction = Transaction.objects.get(user=request.user.id)
    except Transaction.DoesNotExist:
            transaction = None
    
    if transaction is None or transaction.status != "completed":
        return redirect('student:info')

    exercice = Exercice.objects.get(id=exercice_id)

    context = {
        "data": exercice,

student/templates/cancel.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>EducMin</title>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Assistant:wght@200..800&family=Freeman&family=Montserrat:ital,wght@0,100..900;1,100..900&family=Open+Sans:ital,wght@0,300..800;1,300..800&display=swap" rel="stylesheet">
    <script src="https://cdn.tailwindcss.com"></script>
    <script src="{% static 'scripts/tailwind.js' %}"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.2/css/all.min.css" integrity="sha512-SnH5WK+bZxgPHs44uWIX+LLJAJ9/2PkPKZ5QiAj6Ta86w+fsb2TkcmfRyVX3pBnMFcV7oQPJkl9QevSCWr3W6A==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <script>
        tailwind.config = {
          theme: {
            extend: {
              colors: {
                clifford: '#da373d',
                primary: '#ff7e84',
                secondary: '#30bead',
                tertiary: '#ffbc1f',
                redShade: '#8861db',
                dark: '#0c1327',
                fourth: '#dcf2ef',
                fiveth: '#ffebec',
                sixth: '#ffffff'
              },
              flex: {
                '30': '1 1 30rem'
              },
              gridTemplateColumns: {
                'auto-fit': 'repeat(auto-fit, minmax(250px, 1fr))',
              },
              screens: {
                'max-950': {'max': '950px'},
                'max-700': {'max': '700px'},
                'max-635': {'max': '635px'},
                'max-585': {'max': '585px'},
                'max-495': {'max': '495px'},
                'max-395': {'max': '395px'},
                'min-895': '895px'
              },
              spacing: {
                '10p': '10%',
              },
              height: {
                '90': '90%',
                '110': '110vh'
              },
              width: {
                '90': '90%',
                '110': '110vh'
              },
            }
          }
        }
    </script>
</head>
<body>
    <nav class="fixed z-50 w-full p-2 flex items-center justify-around bg-white max-700:justify-between">
        <span class="text-black-600 text-2xl font-bold max-700:text-xl">EduMim</span>
    </nav>
    
    <section class="w-full h-screen z-40 py-8 px-32 bg-gradient-to-r from-fourth to-fiveth flex items-center justify-center flex-col gap-4 max-950:px-4">
      <h1 class="text-xl text-dark font-bold max-635:text-lg">Ouups, quelque chose s'est mal passé</h1>
      <a href="{% url 'student:payement' %}" class="bg-secondary text-lg p-2 w-36 text-center text-white rounded-lg transition duration-300 ease-in-out hover:scale-95">Rééssayer</a>
    </section>
    
    
</body>
</html>

student/templates/cours.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>EducMin</title>    
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Assistant:wght@200..800&family=Freeman&family=Montserrat:ital,wght@0,100..900;1,100..900&family=Open+Sans:ital,wght@0,300..800;1,300..800&display=swap" rel="stylesheet">
    <script src="https://cdn.tailwindcss.com"></script>
    <script src="{% static 'scripts/tailwind.js' %}"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.2/css/all.min.css" integrity="sha512-SnH5WK+bZxgPHs44uWIX+LLJAJ9/2PkPKZ5QiAj6Ta86w+fsb2TkcmfRyVX3pBnMFcV7oQPJkl9QevSCWr3W6A==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <script>
        tailwind.config = {
          theme: {
            extend: {
              colors: {
                clifford: '#da373d',
                primary: '#ff7e84',
                secondary: '#30bead',
                tertiary: '#ffbc1f',
                redShade: '#8861db',
                dark: '#0c1327',
                fourth: '#dcf2ef',
                fiveth: '#ffebec',
                sixth: '#ffffff'
              },
              flex: {
                '30': '1 1 30rem'
              },
              gridTemplateColumns: {
                'auto-fit': 'repeat(auto-fit, minmax(250px, 1fr))',
              },
              screens: {
                'max-950': {'max': '950px'},
                'max-700': {'max': '700px'},
                'max-635': {'max': '635px'},
                'max-585': {'max': '585px'},
                'max-495': {'max': '495px'},
                'max-395': {'max': '395px'},
              },
              spacing: {
                '10p': '10%',
              },
              height: {
                '90': '90%',
                '110': '110vh'
              },
              width: {
                '90': '90%',
                '110': '110vh'
              },
            }
          }
        }
    </script>
</head>
<body>
    <nav class="fixed z-50 w-full p-2 flex items-center justify-around bg-white max-700:justify-between">
        <span class="text-black-600 text-2xl font-bold max-700:text-xl">EduMim</span>
        <ul id="nav" class="flex items-center justify-between gap-8 text-lg text-gray-600 font-semibold max-700:text-base max-585:bg-gray-200 max-585:w-3/4
         max-585:rounded max-585:p-8 max-585:flex-col max-585:absolute max-585:top-16 max-585:left-10p max-585:hidden">
         <li>
          <a class="hover:text-primary hover:font-bold" href="{% url 'student:index' %}">Accueil</a>
          </li>
          <li>
              <a class="hover:text-primary hover:font-bold" href="{% url 'student:matieres' %}">Matières</a>
          </li>
          <li>
              <a class="text-primary font-bold hover:text-primary hover:font-bold" href="{% url 'student:cours' %}">Cours</a>
          </li>
          <li>
              <a class="hover:text-primary hover:font-bold" href="{% url 'student:exercices' %}">Exercices</a>
          </li>
        </ul>
        <div class="flex items-center justify-center gap-5 max-700:gap-3">
          <div class="flex items-center gap-4">
            {% if student.image %}
              <img id="profile" class="w-12 h-12 p-1 rounded-full ring-2 ring-gray-300 object-cover" src="{{ student.image.url }}" alt="profile">
            {% else %}
              <img id="profile" class="w-12 h-12 p-1 rounded-full ring-2 ring-gray-300 object-cover" src="{% static 'img/profile.jpg' %}" alt="profile">
            {% endif %}
          </div>
            <div class="fa-solid fa-bars text-3xl cursor-pointer hidden max-585:block" id="menu-bar"></div>
            <div id="info" class="hidden w-1/5 p-4 flex items-center justify-center flex-col gap-2 rounded-lg bg-gray-100 absolute top-20 drop-shadow-2xl before:w-5 before:h-5 before:bg-gray-100 before:absolute before:-top-2 before:inset-x-auto before:rotate-45 max-950:before:right-10 max-950:w-1/3 max-950:right-10 max-585:w-1/2 max-585:before:inset-x-auto max-395:w-3/4 max-395:right-1">
              <a href="{% url 'student:profile' %}" class="w-full p-2 border-b border-solid border-gray-300 rounded-lg text-lg font-semibold transition duration-300 ease-in-out hover:bg-primary hover:text-white">Voir mon profile</a>
              <a href="{% url 'student:logout' %}" class="w-full p-2 rounded-lg text-lg font-semibold transition duration-300 ease-in-out hover:bg-primary hover:text-white">Deconnexion</a>
            </div>
        </div>
    </nav>
    
    <section class="w-full z-40 py-8 px-32 bg-gradient-to-r from-fourth to-fiveth flex items-center justify-center flex-col gap-4 max-950:px-4">
      <span class="mt-8 text-3xl text-dark font-bold max-700:text-xl max-395:text-lg">Nos <span class="text-primary underline decoration-wavy">Cours</span></span>
      <div class="w-full p-4 grid items-center justify-center max-495:grid-cols-1 max-635:grid-cols-2 sm:grid-cols-2 md:grid-cols-3 2xl:grid-cols-4 gap-4">
        {% if data %}
          {% for cours in data %}
            <div class="flex items-center flex-col max-w-sm bg-white border border-gray-200 rounded-lg shadow transition duration-100 ease-in-out hover:scale-95">
              <div class="self-start w-full h-44 rounded">
                <a href="{% url 'student:show-cours' cours.id %}">
                  {% if cours.img_cours %}
                    <img src="{{ cours.img_cours.url }}" alt="art" class="w-full h-full object-cover rounded-t-lg">
                  {% else %}
                    <img src="{% static 'img/default-cours.jpg' %}" alt="art" class="w-full h-full object-cover rounded-t-lg">
                  {% endif %}
                </a>
                <span class="bg-secondary text-white text-base font-medium me-2 px-2.5 py-0.5 rounded self-start relative -top-40 left-2">{{ cours.de_matiere.nom_matiere }}</span>
              </div>
              <div class="p-5 flex items-center justify-center flex-col gap-4 p-2">
                <a href="{% url 'student:show-cours' cours.id %}">
                  <span class="text-xl text-dark font-bold transition duration-300 ease-in hover:text-primary">{{ cours.nom_cours }}</span>
                </a>                
              </div>
            </div>
          {% endfor %}
        {% else %}
          <p class="text-2xl font-bold text-center">Aucun Cours</p>
        {% endif %}        
      </div>
    </section>
    
    <footer class="w-full py-16 px-32 bg-dark flex items-center justify-center flex-wrap max-950:px-4">
      <div class="p-2 w-full grid grid-cols-1 gap-4 justify-between md:grid-cols-3">
        <div class="p-4 flex items-start justify-center flex-col gap-4">
          <span class="text-3xl text-white font-bold">EduMin</span>
          <p class="text-xm text-gray-600 font-medium text-justify max-700:text-lg max-585:text-base max-495:text-sm max-395:text-xs">
            "L'éducation est l'arme la plus puissante
            que vous pouvez utilisez pour changer le monde."
            --Nelson Mandela
          </p>
          <div class="p-4 w-3/4 flex items-center justify-between gap-2">
            <div class="fa-brands fa-facebook-f flex items-center justify-center text-xl text-white w-10 h-10 p-2 bg-gray-700 rounded transition ease-in-out duration-300 hover:bg-primary"></div>
            <div class="fa-brands fa-instagram flex items-center justify-center text-xl text-white w-10 h-10 p-2 bg-gray-700 rounded transition ease-in-out duration-300 hover:bg-primary"></div>
            <div class="fa-brands fa-twitter flex items-center justify-center text-xl text-white w-10 h-10 p-2 bg-gray-700 rounded transition ease-in-out duration-300 hover:bg-primary"></div>
            <div class="fa-brands fa-linkedin-in flex items-center justify-center text-xl text-white w-10 h-10 p-2 bg-gray-700 rounded transition ease-in-out duration-300 hover:bg-primary"></div>
          </div>
        </div>
        <div class="p-4 flex items-start justify-start flex-col gap-4">
          <span class="text-xl text-white font-bold max-395:text-base">Links</span>
          <a href="{% url 'student:index' %}" class="text-lg text-gray-600 font-medium transition ease-in-out duration-300 transform hover:translate-x-1 hover:underline hover:text-primary max-395:text-sm">Home</a>
          <a href="{% url 'student:matieres' %}" class="text-lg text-gray-600 font-medium transition ease-in-out duration-300 transform hover:translate-x-1 hover:underline hover:text-primary max-395:text-sm">Matiers</a>
          <a href="{% url 'student:cours' %}" class="text-lg text-gray-600 font-medium transition ease-in-out duration-300 transform hover:translate-x-1 hover:underline hover:text-primary max-395:text-sm">Cours</a>
          <a href="{% url 'student:exercices' %}" class="text-lg text-gray-600 font-medium transition ease-in-out duration-300 transform hover:translate-x-1 hover:underline hover:text-primary max-395:text-sm">Exercices</a>
          
        </div>
        <div class="p-4 flex items-start justify-start flex-col gap-4">
          <span class="text-xl text-white font-bold max-395:text-base">Legal</span>
          <a href="#" class="text-lg text-gray-600 font-medium transition ease-in-out duration-300 transform hover:translate-x-1 hover:underline hover:text-primary max-395:text-sm">Tearm & Condition</a>
          <a href="#" class="text-lg text-gray-600 font-medium transition ease-in-out duration-300 transform hover:translate-x-1 hover:underline hover:text-primary max-395:text-sm">Payement Method</a>
          <a href="#" class="text-lg text-gray-600 font-medium transition ease-in-out duration-300 transform hover:translate-x-1 hover:underline hover:text-primary max-395:text-sm">Privacy Policy</a>
          <a href="#" class="text-lg text-gray-600 font-medium transition ease-in-out duration-300 transform hover:translate-x-1 hover:underline hover:text-primary max-395:text-sm">Licensencing</a>
        </div>
      </div>
      
    </footer>
    <script src="{% static 'js/scripts.js' %}"></script>
    <script>
      const info = document.getElementById('info');
      const profile = document.getElementById('profile');

      profile.addEventListener('click', () => {
        info.classList.toggle('hidden');
      });
    </script>
</body>
</html>

student/templates/payement.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>EducMin</title>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Assistant:wght@200..800&family=Freeman&family=Montserrat:ital,wght@0,100..900;1,100..900&family=Open+Sans:ital,wght@0,300..800;1,300..800&display=swap" rel="stylesheet">
    <script src="https://cdn.tailwindcss.com"></script>
    <script src="{% static 'scripts/tailwind.js' %}"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.2/css/all.min.css" integrity="sha512-SnH5WK+bZxgPHs44uWIX+LLJAJ9/2PkPKZ5QiAj6Ta86w+fsb2TkcmfRyVX3pBnMFcV7oQPJkl9QevSCWr3W6A==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <script>
        tailwind.config = {
          theme: {
            extend: {
              colors: {
                clifford: '#da373d',
                primary: '#ff7e84',
                secondary: '#30bead',
                tertiary: '#ffbc1f',
                redShade: '#8861db',
                dark: '#0c1327',
                fourth: '#dcf2ef',
                fiveth: '#ffebec',
                sixth: '#ffffff'
              },
              flex: {
                '30': '1 1 30rem'
              },
              gridTemplateColumns: {
                'auto-fit': 'repeat(auto-fit, minmax(250px, 1fr))',
              },
              screens: {
                'max-950': {'max': '950px'},
                'max-700': {'max': '700px'},
                'max-635': {'max': '635px'},
                'max-585': {'max': '585px'},
                'max-495': {'max': '495px'},
                'max-395': {'max': '395px'},
                'min-895': '895px'
              },
              spacing: {
                '10p': '10%',
              },
              height: {
                '90': '90%',
                '110': '110vh'
              },
              width: {
                '90': '90%',
                '110': '110vh'
              },
            }
          }
        }
    </script>
</head>
<body>
    <nav class="fixed z-50 w-full p-2 flex items-center justify-around bg-white max-700:justify-between">
        <span class="text-black-600 text-2xl font-bold max-700:text-xl">EduMim</span>
    </nav>
    
    <section class="w-full h-screen z-40 py-8 px-32 bg-gradient-to-r from-fourth to-fiveth flex items-center justify-center flex-col gap-4 max-950:px-4">
      <h1 class="text-xl text-dark font-bold max-635:text-lg">Un payement est requis pour pouvoir acceder à la plateforme.</h1>
      <p class="text-xl font-semibold max-635:text-base">Le payement ne vous coutera que la somme de <span class="text-primary font-bold">100F</span></p>
      <a href="{% url 'student:payement' %}" class="bg-secondary text-lg p-2 w-36 text-center text-white rounded-lg transition duration-300 ease-in-out hover:scale-95">Payer</a>
    </section>
    
    
</body>
</html>